[package]
cairo-version = "=2.9.4"
name = "stark_brawl"
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
spawn = "sozo execute dojo_starter-actions spawn --wait"
move = "sozo execute dojo_starter-actions move -c 1 --wait"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.4.0" }
openzeppelin_token = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }


[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.4.0" }
cairo_test = "2.9.4"
